// Generated by gencpp from file robotis_controller_msgs/GetJointModule.msg
// DO NOT EDIT!


#ifndef ROBOTIS_CONTROLLER_MSGS_MESSAGE_GETJOINTMODULE_H
#define ROBOTIS_CONTROLLER_MSGS_MESSAGE_GETJOINTMODULE_H

#include <ros/service_traits.h>


#include <robotis_controller_msgs/GetJointModuleRequest.h>
#include <robotis_controller_msgs/GetJointModuleResponse.h>


namespace robotis_controller_msgs
{

struct GetJointModule
{

typedef GetJointModuleRequest Request;
typedef GetJointModuleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointModule
} // namespace robotis_controller_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotis_controller_msgs::GetJointModule > {
  static const char* value()
  {
    return "55513368a0fa6f6cbd22bf1bfb152faa";
  }

  static const char* value(const ::robotis_controller_msgs::GetJointModule&) { return value(); }
};

template<>
struct DataType< ::robotis_controller_msgs::GetJointModule > {
  static const char* value()
  {
    return "robotis_controller_msgs/GetJointModule";
  }

  static const char* value(const ::robotis_controller_msgs::GetJointModule&) { return value(); }
};


// service_traits::MD5Sum< ::robotis_controller_msgs::GetJointModuleRequest> should match 
// service_traits::MD5Sum< ::robotis_controller_msgs::GetJointModule > 
template<>
struct MD5Sum< ::robotis_controller_msgs::GetJointModuleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotis_controller_msgs::GetJointModule >::value();
  }
  static const char* value(const ::robotis_controller_msgs::GetJointModuleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotis_controller_msgs::GetJointModuleRequest> should match 
// service_traits::DataType< ::robotis_controller_msgs::GetJointModule > 
template<>
struct DataType< ::robotis_controller_msgs::GetJointModuleRequest>
{
  static const char* value()
  {
    return DataType< ::robotis_controller_msgs::GetJointModule >::value();
  }
  static const char* value(const ::robotis_controller_msgs::GetJointModuleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotis_controller_msgs::GetJointModuleResponse> should match 
// service_traits::MD5Sum< ::robotis_controller_msgs::GetJointModule > 
template<>
struct MD5Sum< ::robotis_controller_msgs::GetJointModuleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotis_controller_msgs::GetJointModule >::value();
  }
  static const char* value(const ::robotis_controller_msgs::GetJointModuleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotis_controller_msgs::GetJointModuleResponse> should match 
// service_traits::DataType< ::robotis_controller_msgs::GetJointModule > 
template<>
struct DataType< ::robotis_controller_msgs::GetJointModuleResponse>
{
  static const char* value()
  {
    return DataType< ::robotis_controller_msgs::GetJointModule >::value();
  }
  static const char* value(const ::robotis_controller_msgs::GetJointModuleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTIS_CONTROLLER_MSGS_MESSAGE_GETJOINTMODULE_H
