// Generated by gencpp from file robotis_controller_msgs/SetModule.msg
// DO NOT EDIT!


#ifndef ROBOTIS_CONTROLLER_MSGS_MESSAGE_SETMODULE_H
#define ROBOTIS_CONTROLLER_MSGS_MESSAGE_SETMODULE_H

#include <ros/service_traits.h>


#include <robotis_controller_msgs/SetModuleRequest.h>
#include <robotis_controller_msgs/SetModuleResponse.h>


namespace robotis_controller_msgs
{

struct SetModule
{

typedef SetModuleRequest Request;
typedef SetModuleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetModule
} // namespace robotis_controller_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotis_controller_msgs::SetModule > {
  static const char* value()
  {
    return "fe41ec40765aa76b66cdabcf74584706";
  }

  static const char* value(const ::robotis_controller_msgs::SetModule&) { return value(); }
};

template<>
struct DataType< ::robotis_controller_msgs::SetModule > {
  static const char* value()
  {
    return "robotis_controller_msgs/SetModule";
  }

  static const char* value(const ::robotis_controller_msgs::SetModule&) { return value(); }
};


// service_traits::MD5Sum< ::robotis_controller_msgs::SetModuleRequest> should match 
// service_traits::MD5Sum< ::robotis_controller_msgs::SetModule > 
template<>
struct MD5Sum< ::robotis_controller_msgs::SetModuleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotis_controller_msgs::SetModule >::value();
  }
  static const char* value(const ::robotis_controller_msgs::SetModuleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotis_controller_msgs::SetModuleRequest> should match 
// service_traits::DataType< ::robotis_controller_msgs::SetModule > 
template<>
struct DataType< ::robotis_controller_msgs::SetModuleRequest>
{
  static const char* value()
  {
    return DataType< ::robotis_controller_msgs::SetModule >::value();
  }
  static const char* value(const ::robotis_controller_msgs::SetModuleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotis_controller_msgs::SetModuleResponse> should match 
// service_traits::MD5Sum< ::robotis_controller_msgs::SetModule > 
template<>
struct MD5Sum< ::robotis_controller_msgs::SetModuleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotis_controller_msgs::SetModule >::value();
  }
  static const char* value(const ::robotis_controller_msgs::SetModuleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotis_controller_msgs::SetModuleResponse> should match 
// service_traits::DataType< ::robotis_controller_msgs::SetModule > 
template<>
struct DataType< ::robotis_controller_msgs::SetModuleResponse>
{
  static const char* value()
  {
    return DataType< ::robotis_controller_msgs::SetModule >::value();
  }
  static const char* value(const ::robotis_controller_msgs::SetModuleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTIS_CONTROLLER_MSGS_MESSAGE_SETMODULE_H
