// Generated by gencpp from file robotis_controller_msgs/WriteControlTable.msg
// DO NOT EDIT!


#ifndef ROBOTIS_CONTROLLER_MSGS_MESSAGE_WRITECONTROLTABLE_H
#define ROBOTIS_CONTROLLER_MSGS_MESSAGE_WRITECONTROLTABLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotis_controller_msgs
{
template <class ContainerAllocator>
struct WriteControlTable_
{
  typedef WriteControlTable_<ContainerAllocator> Type;

  WriteControlTable_()
    : joint_name()
    , start_item_name()
    , data_length(0)
    , data()  {
    }
  WriteControlTable_(const ContainerAllocator& _alloc)
    : joint_name(_alloc)
    , start_item_name(_alloc)
    , data_length(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _joint_name_type;
  _joint_name_type joint_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _start_item_name_type;
  _start_item_name_type start_item_name;

   typedef uint16_t _data_length_type;
  _data_length_type data_length;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> const> ConstPtr;

}; // struct WriteControlTable_

typedef ::robotis_controller_msgs::WriteControlTable_<std::allocator<void> > WriteControlTable;

typedef boost::shared_ptr< ::robotis_controller_msgs::WriteControlTable > WriteControlTablePtr;
typedef boost::shared_ptr< ::robotis_controller_msgs::WriteControlTable const> WriteControlTableConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotis_controller_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'robotis_controller_msgs': ['/home/shengjie/catkin_ws/src/ROBOTIS-Framework-msgs/robotis_controller_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d4e0e3e28ede43d877e2fb8f0a1a011";
  }

  static const char* value(const ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d4e0e3e28ede43dULL;
  static const uint64_t static_value2 = 0x877e2fb8f0a1a011ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotis_controller_msgs/WriteControlTable";
  }

  static const char* value(const ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string joint_name\n\
string start_item_name\n\
uint16 data_length\n\
uint8[] data\n\
";
  }

  static const char* value(const ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_name);
      stream.next(m.start_item_name);
      stream.next(m.data_length);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteControlTable_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotis_controller_msgs::WriteControlTable_<ContainerAllocator>& v)
  {
    s << indent << "joint_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint_name);
    s << indent << "start_item_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.start_item_name);
    s << indent << "data_length: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.data_length);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIS_CONTROLLER_MSGS_MESSAGE_WRITECONTROLTABLE_H
