(cl:defpackage robotis_controller_msgs-srv
  (:use )
  (:export
   "GETJOINTMODULE"
   "<GETJOINTMODULE-REQUEST>"
   "GETJOINTMODULE-REQUEST"
   "<GETJOINTMODULE-RESPONSE>"
   "GETJOINTMODULE-RESPONSE"
   "LOADOFFSET"
   "<LOADOFFSET-REQUEST>"
   "LOADOFFSET-REQUEST"
   "<LOADOFFSET-RESPONSE>"
   "LOADOFFSET-RESPONSE"
   "SETJOINTMODULE"
   "<SETJOINTMODULE-REQUEST>"
   "SETJOINTMODULE-REQUEST"
   "<SETJOINTMODULE-RESPONSE>"
   "SETJOINTMODULE-RESPONSE"
   "SETMODULE"
   "<SETMODULE-REQUEST>"
   "SETMODULE-REQUEST"
   "<SETMODULE-RESPONSE>"
   "SETMODULE-RESPONSE"
  ))

